  
version: "3.3"
volumes:
   qtumd-volume:

services:
  janus:
    image: qtum/janus
    container_name: janus_testchain
    build: 
        context: ../../
        cache_from:
          - golang:1.14-alpine
    ports:
        - "23889:23889"
    environment: 
        - QTUM_RPC=http://qtum:testpasswd@qtum:3889
    volumes:
        - ../standalone/myaccounts.txt:$GOPATH/github.com/qtumproject/janus/myaccounts.txt
        - ../../https:/https
    depends_on:
      - qtum
    command: --bind 0.0.0.0 --ignoreTransactions --accounts $GOPATH/github.com/qtumproject/janus/myaccounts.txt --dev --https-key /https/key.pem --https-cert /https/cert.pem
  qtum:
    ports:
      - "3889:3889"
    image: qtum/qtum
    container_name: qtum_testchain
    command: qtumd -testnet -txindex -addrindex=1 -rpcbind=0.0.0.0:3889 -rpcallowip=0.0.0.0/0 -logevents -rpcuser=qtum -rpcpassword=testpasswd -deprecatedrpc=accounts -printtoconsole
    volumes:
      - qtumd-volume
